name: Validate for PR
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.23'
      - name: Install dependencies
        run: make deps
      - name: Unit test
        run: make ci-test
      - name: Linting
        run: make lint
      - name: Acceptance test
        run: make build acceptance-test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
