name: Validate for PR
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.23'
      - name: Unit Test
        run: make ci-test
      - name: Acceptance Test
        run: make acceptance-test
      - name: Coverate report
        run: make coverage-report
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          exclude: test
