name: Release workflow
on:
  push:
    tags:
      - 'v*'
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - uses: actions/setup-go@v1
        env:
          GO111MODULE: on
        with:
          go-version: '1.23'
      - name: Unit Test
        run: make ci-test
      - name: Acceptance Test
        run: make acceptance-test
      - name: Coverate report
        run: make coverage-report
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          files: tmp/coverage/ci-test.txt,tmp/coverage/acceptance.txt
